/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:536094f1-b62f-49af-9335-2a8df2d0b155",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xVm5uOcSa",
    "aws_user_pools_web_client_id": "4gl5u66j7ml0nukm60emm56i9b",
    "oauth": {
        "domain": "letterboxdclone484b49d6-484b49d6-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
