version: '2'
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - '8080:8080'
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - '5432:5432'